/* eslint-disable no-dupe-keys */
import { Checkbox, Icon } from "rsuite";
export const data = [
  {
    id: <Checkbox />,
    status: <Icon icon="check-circle" size="lg" style={{ color: "green" }} />,
    title: "New Amieshire",
    type: "New Amieshire",
    status: <Icon icon="check-circle" size="lg" style={{ color: "green" }} />,
    title: "New Amieshire",
    type: "New Amieshire",
    avartar: "https://s3.amazonaws.com/uifaces/faces/twitter/justinrob/128.jpg",
    city: "New Amieshire",
    email: "Leora13@yahoo.com",
    firstName:
      "Ernest Schuppe SchuppeSchuppeSchuppeSchuppeSchuppeSchuppe Schuppe",
    lastName: "Schuppe",
    street: "Ratke Port",
    zipCode: "17026-3154",
    date: "2016-09-23T07:57:40.195Z",
    bs: "global drive functionalities",
    catchPhrase: "Intuitive impactful software",
    words: "saepe et omnis",
    sentence: "Quos aut sunt id nihil qui.",
    stars: 820,
    followers: 70,
  },
  {
    id: <Checkbox />,
    status: <Icon icon="check-circle" size="lg" style={{ color: "green" }} />,
    title: "New Amieshire",
    type: "New Amieshire",
    avartar:
      "https://s3.amazonaws.com/uifaces/faces/twitter/thaisselenator_/128.jpg",
    city: "New Gust",
    email: "Mose_Gerhold51@yahoo.com",
    firstName: "Janis",
    lastName: "Vandervort",
    street: "Dickinson Keys",
    zipCode: "43767",
    date: "2017-03-06T09:59:12.551Z",
    bs: "e-business maximize bandwidth",
    catchPhrase: "De-engineered discrete secured line",
    companyName: "Glover - Hermiston",
    words: "deleniti dolor nihil",
    sentence: "Illo quidem libero corporis laborum.",
    stars: 1200,
    followers: 170,
  },
  {
    id: <Checkbox />,
    status: <Icon icon="check-circle" size="lg" style={{ color: "green" }} />,
    title: "New Amieshire",
    type: "New Amieshire",
    avartar: "https://s3.amazonaws.com/uifaces/faces/twitter/arpitnj/128.jpg",
    city: "Lefflerstad",
    email: "Frieda.Sauer61@gmail.com",
    firstName: "Makenzie",
    lastName: "Bode",
    street: "Legros Divide",
    zipCode: "54812",
    date: "2016-12-08T13:44:26.557Z",
    bs: "plug-and-play e-enable content",
    catchPhrase: "Ergonomic 6th generation challenge",
    companyName: "Williamson - Kassulke",
    words: "quidem earum magnam",
    sentence: "Nam qui perferendis ut rem vitae saepe.",
    stars: 610,
    followers: 170,
  },
  {
    id: <Checkbox />,
    status: <Icon icon="check-circle" size="lg" style={{ color: "green" }} />,
    title: "New Amieshire",
    type: "New Amieshire",
    avartar:
      "https://s3.amazonaws.com/uifaces/faces/twitter/brajeshwar/128.jpg",
    city: "East Catalina",
    email: "Eloisa.OHara@hotmail.com",
    firstName: "Ciara",
    lastName: "Towne",
    street: "Schimmel Ramp",
    zipCode: "76315-2246",
    date: "2016-07-19T12:54:30.994Z",
    bs: "extensible innovate e-business",
    catchPhrase: "Upgradable local model",
    companyName: "Hilpert, Eichmann and Brown",
    words: "exercitationem rerum sit",
    sentence: "Qui rerum ipsa atque qui.",
    stars: 5322,
    followers: 170,
  },
  {
    id: <Checkbox />,
    status: <Icon icon="check-circle" size="lg" style={{ color: "green" }} />,
    title: "New Amieshire",
    type: "New Amieshire",
    avartar:
      "https://s3.amazonaws.com/uifaces/faces/twitter/dev_essentials/128.jpg",
    city: "Ritchieborough",
    email: "Brisa46@hotmail.com",
    firstName: "Suzanne",
    lastName: "Wolff",
    street: "Lemuel Radial",
    zipCode: "88870-3897",
    date: "2017-02-23T17:11:53.875Z",
    bs: "back-end orchestrate networks",
    catchPhrase: "Exclusive human-resource knowledge base",
    companyName: "Mayer - Considine",
    words: "voluptatum tempore at",
    sentence: "Enim quia deleniti molestiae aut.",
    stars: 852,
    followers: 770,
  },
  {
    id: <Checkbox />,
    status: <Icon icon="check-circle" size="lg" style={{ color: "green" }} />,
    title: "New Amieshire",
    type: "New Amieshire",
    avartar: "https://s3.amazonaws.com/uifaces/faces/twitter/petrangr/128.jpg",
    city: "Lake Emery",
    email: "Cody.Schultz56@gmail.com",
    firstName: "Alessandra",
    lastName: "Feeney",
    street: "Mosciski Estate",
    zipCode: "81514",
    date: "2016-06-30T05:23:18.734Z",
    bs: "sexy evolve technologies",
    catchPhrase: "Virtual hybrid throughput",
    companyName: "Nikolaus and Sons",
    words: "alias minus repudiandae",
    sentence: "Sed qui eius excepturi sunt voluptates.",
    stars: 3209,
    followers: 2780,
  },
];
